// Presets only define light colors. Dark values are auto-generated by the engine.
export interface PresetDef {
  id: string;
  name: string;
  description: string;
  colors: Array<{ name: string; variable: string; light: string }>;
}

export const PRESETS: PresetDef[] = [
  {
    id: 'semantic-full',
    name: 'Semantic Full',
    description: 'Primary, secondary, neutral, success, warning, error, info — ideal para cualquier producto',
    colors: [
      { name: 'Primary',   variable: 'primary',   light: 'oklch(0.45 0.22 264)' },
      { name: 'Secondary', variable: 'secondary', light: 'oklch(0.45 0.15 300)' },
      { name: 'Neutral',   variable: 'neutral',   light: 'oklch(0.40 0.01 250)' },
      { name: 'Success',   variable: 'success',   light: 'oklch(0.52 0.17 145)' },
      { name: 'Warning',   variable: 'warning',   light: 'oklch(0.65 0.20 75)'  },
      { name: 'Error',     variable: 'error',     light: 'oklch(0.52 0.24 25)'  },
      { name: 'Info',      variable: 'info',      light: 'oklch(0.55 0.18 220)' },
    ],
  },
  {
    id: 'saas-minimal',
    name: 'SaaS Minimal',
    description: 'Azul/índigo elegante con neutrales fríos para apps B2B',
    colors: [
      { name: 'Primary',  variable: 'primary',  light: 'oklch(0.48 0.24 256)' },
      { name: 'Neutral',  variable: 'neutral',  light: 'oklch(0.38 0.01 260)' },
      { name: 'Success',  variable: 'success',  light: 'oklch(0.52 0.17 145)' },
      { name: 'Error',    variable: 'error',    light: 'oklch(0.52 0.24 25)'  },
    ],
  },
  {
    id: 'dark-first',
    name: 'Dark First',
    description: 'Paleta pensada desde el modo oscuro. Vibrante sobre fondos oscuros',
    colors: [
      { name: 'Primary',  variable: 'primary',  light: 'oklch(0.62 0.26 280)' },
      { name: 'Accent',   variable: 'accent',   light: 'oklch(0.60 0.25 180)' },
      { name: 'Neutral',  variable: 'neutral',  light: 'oklch(0.32 0.01 280)' },
      { name: 'Error',    variable: 'error',    light: 'oklch(0.55 0.24 25)'  },
    ],
  },
  {
    id: 'editorial',
    name: 'Editorial',
    description: 'Alto contraste, tonos tierra y sepia. Para blogs, revistas y portfolios',
    colors: [
      { name: 'Primary', variable: 'primary', light: 'oklch(0.36 0.08 50)' },
      { name: 'Accent',  variable: 'accent',  light: 'oklch(0.48 0.16 25)' },
      { name: 'Base',    variable: 'base',    light: 'oklch(0.97 0.01 80)' },
      { name: 'Neutral', variable: 'neutral', light: 'oklch(0.42 0.01 80)' },
    ],
  },
  {
    id: 'acss',
    name: 'ACSS Compatible',
    description: 'Convención ACSS: primary, secondary, tertiary, accent, base, neutral',
    colors: [
      { name: 'Primary',   variable: 'primary',   light: 'oklch(0.45 0.22 264)' },
      { name: 'Secondary', variable: 'secondary', light: 'oklch(0.50 0.18 220)' },
      { name: 'Tertiary',  variable: 'tertiary',  light: 'oklch(0.48 0.16 175)' },
      { name: 'Accent',    variable: 'accent',    light: 'oklch(0.62 0.24 310)' },
      { name: 'Base',      variable: 'base',      light: 'oklch(0.98 0.00 0)'   },
      { name: 'Neutral',   variable: 'neutral',   light: 'oklch(0.40 0.01 250)' },
    ],
  },
];
